config/routes.rb
Rails.application.routes.draw do
  root 'sessions#index'

  get "/signup", to: "users#new"
  get "/signin", to: "sessions#new"
  post "/sessions", to: "sessions#create"
  delete "/sessions", to: "sessions#destroy", as: 'delete_session'

  resources :users
  resources :attractions
  resources :rides


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attraction.rb
class Attraction < ApplicationRecord
  has_many :rides
  has_many :users, through: :rides

  validates :name, presence: true
  # validates :min_height, numericality: {}
  # validates :nausea_rating
  # validates :happiness_rating
  # validates :ticket_number

end

app/models/ride.rb
class Ride < ActiveRecord::Base
  belongs_to :attraction
  belongs_to :user

  def take_ride
  
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :rides
  has_many :attractions, through: :rides
  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authorized

  helper_method :logged_in?, :current_user

  helper :all


  def current_user
    if session[:user_id]
      User.find(session[:user_id])
    end
  end


  def logged_in?
     !!current_user
  end

  def authorized
    redirect_to signin_path unless logged_in?
  end

end

app/controllers/attractions_controller.rb
class AttractionsController < ApplicationController
  def index
    @attractions = Attraction.all
    # byebug
    # @user = @attractions.users
  end

  def show
    @user = User.find(params[:id])
    @attraction = Attraction.find(params[:id])
  end

  def new
    @attraction = Attraction.new
  end

  def create
    #come back to this for log in stuff
    @attraction = Attraction.new(attraction_params)
    if @attraction.save
      redirect_to attraction_path(@attraction)
    else
      flash[:error] = @attraction.errors.full_messages
      redirect_to new_attraction_path
    end
  end

  def edit
    @attraction = Attraction.find(params[:id])

  end

  def update
    @attraction = Attraction.find(params[:id])
    if @attraction.update(attraction_params)
      redirect_to attraction_path(@attraction)
    else
      flash[:error] = @attraction.errors.full_messages
      redirect_to edit_attraction_path(@attraction)
    end

  end

  def delete
    @attraction = Attraction.find(params[:id])
    @attraction.destroy
    redirect_to attractions_path
  end

  private

  def attraction_params
    params.require(:attraction).permit(:name, :tickets, :nausea_rating, :happiness_rating, :min_height)
  end



end

app/controllers/rides_controller.rb
class RidesController < ApplicationController

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorized, only: [:index, :new, :create]

  def index
    "FU"
  end

  def new
  end

  def create
    @user = User.find_by(name: params[:name])
      if @user && @user.authenticate(params[:password])
        # YOU ARE WHO YOU SAY YOU ARE
        session[:user_id] = @user.id
        redirect_to user_path(@user)
      else
        flash[:error] = ["Username and password do not match"]
        redirect_to signin_path
      end
    end


    def destroy
      # when you're logged out'
      session[:user_id] = nil
      # you should also be redirected
      redirect_to root_path
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]

  def index
    @users = User.all
  end

  def show
    if logged_in?
      if !flash[:msg]
        flash[:msg] = "Welcome back to the theme park!"
      end
    end
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      session[:user_id] = @user.id
      flash[:msg] = "Welcome to the theme park!"
      redirect_to user_path(@user)
    else
      flash[:error] = @user.errors.full_messages
      redirect_to new_user_path
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      flash[:error] = @user.errors.full_messages
      redirect_to edit_user_path(@user)
    end

  end

  def delete
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation, :nausau, :happiness, :tickets, :height, :admin)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attractions_helper.rb
module AttractionsHelper
end

app/helpers/rides_helper.rb
module RidesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attractions/_form.html.erb
<%= form_for @attraction do |f| %>
<%= f.label :name %><br>
<%= f.text_field :name %><br>
<%= f.label :"Height Requirement (in inches)" %><br>
<%= f.number_field :min_height %><br>
<%= f.label :"How fun is it? (1-5 scale)" %><br>
<%= f.number_field :happiness_rating %><br>
<%= f.label :"How nausea-inducing is it? (1-5 scale)" %> <br>
<%= f.number_field :nausea_rating %><br>
<%= f.label :"How many tickets does it cost?"%><br>
<%= f.number_field :tickets %><br>
<br><%= f.submit %>

<% end %>

<%= link_to "Show", @attraction%> | <%=link_to "Back", attractions_path %>

app/views/attractions/edit.html.erb
<h1>Editing attraction</h1>
<%= render 'form' %>

app/views/attractions/index.html.erb
<h1> Listing attractions </h1>

<table>
  <tr>
    <th>Picture</th>
    <th>Name</th>
    <th>Tickets</th>
    <th>Details</th>
  </tr>

<% @attractions.each do |attract| %>
<tr>
  <td>PICTURE</td>
  <td><%= attract.name %></td>
  <td><%= attract.tickets%></td>
  <td><%= link_to "Go on #{attract.name}", attract%></td>
</tr>
<% end %>


</table>

app/views/attractions/new.html.erb
<h1>New attraction</h1>
<%= render 'form' %>

app/views/attractions/show.html.erb
<p>Name: <%= @attraction.name %></p>
<p>Total Number of Users: <%=@attraction.users.count%></p>
<p>Ticket Requirement: <%=@attraction.tickets%></p>
<p>Height Requirement: <%=@attraction.min_height%></p>
<p>Nauseau Rating: <%= @attraction.nausea_rating%></p>
<p>Happiness Rating: <%= @attraction.happiness_rating%></p>

<% if @user.admin %>
  <%= link_to "Edit Attraction", edit_attraction_path(@attraction) %><br>
<% else %>
  <%= button_tag "Go on this ride" %><br>
<% end %>

<%= link_to "Back", attractions_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAmusementPark</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        <a class="navbar-brand" href="<%= root_url %>"/>Home</a>
        <% if current_user %>
          <a class="navbar-brand" href="<%= user_path(current_user) %>"/>Hello, <%=current_user.name%>!</a>
        <a class="navbar-brand" href="<%= attractions_path %>"/>Attractions</a>
        <%= link_to("Logout", delete_session_path, {method: :delete, class: "navbar-brand"}) %>
        <% else %>
        <a class="navbar-brand" href="<%= new_user_path %>"/>Sign Up</a>
        <a class="navbar-brand" href="<%= signin_path %>"/>Sign In</a>
        <% end %>


        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">

          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <!-- content -->
    <div class="container"  role="main">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/_form.html.erb
<% if flash[:error] %>
  <% flash[:error].each do |error| %>
    <%= error %>
  <% end %>
<% end %>


<%= form_for @user do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>
  <%= f.label :password %><br>
  <%= f.password_field :password, placeholder: "Enter Password" %><br>
  <%= f.password_field :password_confirmation, placeholder: "Confirm Password" %><br>
  <%= f.label :"Height (in Inches)" %><br>
  <%= f.number_field :height %><br>
  <%= f.label :"How happy are you? (1-5 scale)" %><br>
  <%= f.number_field :happiness %><br>
  <%= f.label :"How nauseous are you? (1-5 scale)" %> <br>
  <%= f.number_field :nausea %><br>
  <%= f.label :"How many dollars are in your pocket?" %><br>
  <%= f.number_field :tickets %><br>
  <!-- may have to come back to tickets to convert to money -->
  <%= f.label :"Check box if you are a theme park owner" %>
  <%= f.check_box :admin  %><br>
  <%= f.submit %>

  <% end %>

  <%= link_to "Show", @user%> | <%=link_to "Back", users_path %>

app/views/users/edit.html.erb
<h1>Editing user </h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1>Users</h1>

<ul><%= @users.each do |user| %>
  <li><%=link_to user.name, user %> </li>
  <% end %> </ul>

app/views/users/new.html.erb
<h1>New User</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<% if flash[:msg] %>
  <%= flash[:msg] %>
<% end %>

<h1> <%= @user.name %> </h1>

<!-- <p>Mood: <%= %></p> -->
<p>Tickets: <%= @user.tickets%></p>
<p>Height: <%= @user.height %></p>


<%= link_to "Edit", edit_user_path(@user) %><br>
<%= link_to "See attractions", attractions_path%>